apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookservice-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bookservice
  namespaceSelector:
    matchNames:
      - bookservice
  endpoints:
    - port: http
      path: /metrics
      interval: 15s