apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "AppUser"
  RABBITMQ_DEFAULT_PASS: "AppPassword123!"
  RABBITMQ_ERLANG_COOKIE: "RABBITMQCOOKIE123456"