global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'book-service'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'gateway'
    static_configs:
      - targets: ['apigateway:8080']