apiVersion: v1
kind: ConfigMap
metadata:
  name: orderworker-config
  namespace: bookservice
data:
  RabbitMQ__Host: "rabbitmq.rabbitmq.svc.cluster.local"
  RabbitMQ__VirtualHost: "/"
  ZipkinSettings__Path: "http://zipkin:9411/api/v2/spans"