apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderworker
  namespace: bookservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderworker
  template:
    metadata:
      labels:
        app: orderworker
    spec:
      containers:
        - name: orderworker
          image: orderworker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: orderworker-config
            - secretRef:
                name: orderworker-secret
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"