apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconsumerworker
  namespace: bookservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconsumerworker
  template:
    metadata:
      labels:
        app: kafkaconsumerworker
    spec:
      containers:
        - name: kafkaconsumerworker
          image: kafkaconsumerworker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: kafkaconsumerworker-config
            - secretRef:
                name: kafkaconsumerworker-secret
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"