apiVersion: v1
kind: ConfigMap
metadata:
  name: bookservice-config
  namespace: bookservice
data:
  MySettings__ApiKey: "123456"
  MySettings__MaxItems: "50"
  AsyncSettings__AsyncDelayInMilliseconds: "5"

  RabbitMQ__Host: "rabbitmq.rabbitmq.svc.cluster.local"
  RabbitMQ__VirtualHost: "/"

  RedisSettings__ConnectionString: "redis.redis.svc.cluster.local:6379"
  KafkaSettings__BootstrapServers: "my-cluster-kafka-bootstrap.kafka:9092"
  KafkaSettings__Topic: "book-events"

  ZipkinSettings__Path: "http://zipkin:9411/api/v2/spans"