apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer-test-config
  namespace: kafka
data:
  KafkaSettings__BootstrapServers: "my-cluster-kafka-bootstrap.kafka:9092"
  KafkaSettings__Topic: "test-topic"
  RedisSettings__Host: "redis.redis.svc.cluster.local"
  RedisSettings__Port: "6379"
  RabbitMQ__Host: "rabbitmq.rabbitmq.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Exchange: "test-exchange"
  RabbitMQ__Queue: "test-queue"
  RabbitMQ__RoutingKey: "test-key"