apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer-test-config
  namespace: kafka
data:
  KafkaSettings__BootstrapServers: "my-cluster-kafka-bootstrap.kafka:9092"
  KafkaSettings__Topic: "test-topic"